#!/usr/bin/env python3
"""
Auto-generate TODO.md from GitHub Issues
Triggered by GitHub Actions on issue changes
"""

import os
import sys
import json
import requests
from datetime import datetime
from collections import defaultdict

# Configuration
GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN')
REPO = os.environ.get('REPO')  # format: "owner/repo"
API_BASE = 'https://api.github.com'

if not GITHUB_TOKEN or not REPO:
    print("❌ Error: GITHUB_TOKEN and REPO environment variables required")
    sys.exit(1)

headers = {
    'Authorization': f'Bearer {GITHUB_TOKEN}',
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28'
}

def fetch_issues():
    """Fetch all issues from GitHub"""
    url = f'{API_BASE}/repos/{REPO}/issues'
    params = {
        'state': 'all',
        'per_page': 100
    }
    
    response = requests.get(url, headers=headers, params=params)
    response.raise_for_status()
    
    # Filter out pull requests (they also appear in /issues endpoint)
    issues = [issue for issue in response.json() if 'pull_request' not in issue]
    return issues

def categorize_issues(issues):
    """Categorize issues by priority and milestone"""
    categories = {
        'priority-1': {'name': '🔥 Priority 1', 'issues': []},
        'priority-2': {'name': '📌 Priority 2', 'issues': []},
        'priority-3': {'name': '💡 Priority 3', 'issues': []},
        'other': {'name': '📋 Other', 'issues': []}
    }
    
    for issue in issues:
        labels = [label['name'] for label in issue['labels']]
        
        # Determine priority
        if any('priority-high' in l or 'v5.1' in l for l in labels):
            category = 'priority-1'
        elif any('priority-medium' in l or 'v5.2' in l for l in labels):
            category = 'priority-2'
        elif any('priority-low' in l for l in labels):
            category = 'priority-3'
        else:
            category = 'other'
        
        categories[category]['issues'].append(issue)
    
    return categories

def generate_markdown(categories):
    """Generate TODO.md markdown content"""
    lines = []
    
    # Header
    lines.append("# TODO List")
    lines.append("")
    lines.append("> **🤖 Auto-generated from GitHub Issues**  ")
    lines.append("> Last updated: " + datetime.now().strftime("%Y-%m-%d %H:%M UTC"))
    lines.append("")
    lines.append("This file is automatically generated from [GitHub Issues]"
                 f"(https://github.com/{REPO}/issues). ")
    lines.append("All changes are synced automatically.")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # Statistics
    total_issues = sum(len(cat['issues']) for cat in categories.values())
    closed_issues = sum(1 for cat in categories.values() 
                       for issue in cat['issues'] if issue['state'] == 'closed')
    open_issues = total_issues - closed_issues
    
    if total_issues > 0:
        progress = int((closed_issues / total_issues) * 100)
        progress_bar = '█' * (progress // 10) + '░' * (10 - progress // 10)
        lines.append(f"## 📊 Overall Progress")
        lines.append("")
        lines.append(f"**{closed_issues}/{total_issues}** tasks completed ({progress}%)")
        lines.append("")
        lines.append(f"`{progress_bar}` {progress}%")
        lines.append("")
        lines.append("---")
        lines.append("")
    
    # Issues by category
    for priority_key in ['priority-1', 'priority-2', 'priority-3', 'other']:
        category = categories[priority_key]
        
        if not category['issues']:
            continue
        
        lines.append(f"## {category['name']}")
        lines.append("")
        
        # Group by milestone
        by_milestone = defaultdict(list)
        for issue in category['issues']:
            milestone = issue.get('milestone', {}).get('title', 'No Milestone') if issue.get('milestone') else 'No Milestone'
            by_milestone[milestone].append(issue)
        
        for milestone, issues in sorted(by_milestone.items()):
            if milestone != 'No Milestone':
                lines.append(f"### {milestone}")
                lines.append("")
            
            # Calculate progress for this group
            total = len(issues)
            closed = sum(1 for i in issues if i['state'] == 'closed')
            if total > 0:
                pct = int((closed / total) * 100)
                bar = '█' * (pct // 10) + '░' * (10 - pct // 10)
                lines.append(f"**Progress:** `{bar}` {closed}/{total} ({pct}%)")
                lines.append("")
            
            # List issues
            for issue in sorted(issues, key=lambda x: x['number']):
                number = issue['number']
                title = issue['title']
                state = issue['state']
                url = issue['html_url']
                
                # Checkbox (checked if closed)
                checkbox = '[x]' if state == 'closed' else '[ ]'
                
                # Labels
                labels = [l['name'] for l in issue['labels']]
                label_badges = ' '.join(f'`{l}`' for l in labels if not l.startswith('priority-'))
                
                # Format line
                line = f"- {checkbox} **[#{number}]({url})** - {title}"
                if label_badges:
                    line += f" {label_badges}"
                
                lines.append(line)
            
            lines.append("")
        
        lines.append("---")
        lines.append("")
    
    # Footer
    lines.append("## 📝 Notes")
    lines.append("")
    lines.append("- This file is auto-generated - **do not edit manually**")
    lines.append("- Create/edit issues on GitHub to update this file")
    lines.append("- Changes sync automatically via GitHub Actions")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"**Last sync:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} UTC  ")
    lines.append(f"**Repository:** [{REPO}](https://github.com/{REPO})  ")
    lines.append(f"**Issues:** [View all →](https://github.com/{REPO}/issues)")
    
    return '\\n'.join(lines)

def main():
    """Main execution"""
    print("🔄 Fetching issues from GitHub...")
    
    try:
        issues = fetch_issues()
        print(f"✅ Found {len(issues)} issues")
        
        print("📊 Categorizing issues...")
        categories = categorize_issues(issues)
        
        print("📝 Generating TODO.md...")
        markdown = generate_markdown(categories)
        
        # Write to file
        with open('TODO.md', 'w', encoding='utf-8') as f:
            f.write(markdown)
        
        print("✅ TODO.md generated successfully!")
        
        # Print summary
        for cat_key, cat_data in categories.items():
            count = len(cat_data['issues'])
            if count > 0:
                print(f"  {cat_data['name']}: {count} issues")
        
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == '__main__':
    main()
